### ISSUE TITLE
"Find the Hidden One" links to windows but build requires linux

### ISSUE THREAD

**Issue by framerate** [game-ci/steam-deploy#41] opened 2022-07-13 19:27 UTC
I'm setting up this action and trying to setup env variables from an ubuntu machine running steamcmd. I figured this is best since this action requires ubuntu

However the readme directs me to a SECOND ssfn file that is hidden but linux does not appear to have any, hidden or otherwise. Just the one.

I'd like to fix this and then update the documentation, but could someone point me in the right direction?

**Comment by framerate** [comment] 2022-07-14 01:16
FWIW: I used the NOT hidden one and it seems to be building all three OS's for me... so maybe that step is deprecated?

**Comment by davidmfinol** [comment] 2022-09-26 20:54
This is a problem with our documentation, where we are only showing the path for Windows.

We need to update our documentation to include the paths for Mac and Linux as well.

I'm closing this issue as a duplicate of https://github.com/game-ci/steam-deploy/issues/38

**Closed as completed** 2022-09-26 20:55 UTC
Labels: bug
